import {
  DashboardIcon,
  GridViewIcon,
  ViewListIcon,
  RiceIcon,
  OrderAdjustmentColumnIcon,
  PrintIcon,
  ChatIcon,
  SettingIcon,
  ChartBarIcon,
  ChevronDownIcon,
  QrcodeIcon,
  UserCircleIcon,
  AddIcon,
  RefreshIcon,
  Table2Icon,
  Edit2Icon,
  SearchIcon,
  MoneyIcon,
  ShopIcon,
  CheckCircleIcon,
  FileIcon,
  UserIcon,
  LockOnIcon,
  MenuFoldIcon,
  MenuUnfoldIcon,
  EllipsisIcon,
  HistoryIcon
} from 'tdesign-icons-vue-next';

// 单一图标清单：main.ts 全局注册与 router 的 meta.icon 都从这里取。
// 键名即组件名，与 router 侧栏菜单 / AdminLayout tabbar 里的字符串一一对应。
export const iconRegistry = {
  DashboardIcon,
  GridViewIcon,
  ViewListIcon,
  RiceIcon,
  OrderAdjustmentColumnIcon,
  PrintIcon,
  ChatIcon,
  SettingIcon,
  ChartBarIcon,
  ChevronDownIcon,
  QrcodeIcon,
  UserCircleIcon,
  AddIcon,
  RefreshIcon,
  Table2Icon,
  Edit2Icon,
  SearchIcon,
  MoneyIcon,
  ShopIcon,
  CheckCircleIcon,
  FileIcon,
  UserIcon,
  LockOnIcon,
  MenuFoldIcon,
  MenuUnfoldIcon,
  EllipsisIcon,
  HistoryIcon
};
